services:
  node:
    build: ./docker/node
    ports:
      - "4200:4200"
    volumes:
      - ".:/projects"
    tty: true
  api:
    # image: my-express-container
    # container_name: my-express-api
    build:
      context: ./express
    ports:
      - "8001:8000"
  db:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
        - ${DB_PORT}:3306
    volumes:
        - db-store:/var/lib/mysql
        - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf
volumes:
  db-store: